version: "3.7"

services:
  # db:
  #   image: postgres:10.1-alpine

    # environment:
    #
    #   POSTGRES_PASSWORD: a123

  django_project:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/usr/src/online-shop
    ports:
      - 8001:8001
    # depends_on:
    #   - db
