# Generated by Django 4.1.3 on 2022-11-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_order_date_added_shippingaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="country",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="zip_code",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
