# Generated by Django 4.1.3 on 2022-11-22 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0011_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="customer",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
