# Generated by Django 4.1.3 on 2022-12-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_websocketinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="websocketinfo",
            name="last_usd_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="websocketinfo",
            name="last_usd_exchange_rate",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
