# Generated by Django 4.1.3 on 2024-06-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="session_key",
            field=models.CharField(default="", max_length=36),
        ),
    ]
